### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by PoLaKoSz** [DoubleHub/CSGOCheatMaking101#3]
Hi!

I removed the BB codes and formatted the tutorial with Markdown. Do You still update the forum post? If not [You can find here](https://github.com/PoLaKoSz/CSGOCheatMaking101/blob/dev/markdown/Guide.md) my modification. _If You like it I can make a PR_. :smile:

**Comment by giovanni-orciuolo** [comment]
Ok! Thank you for the support

**Comment by PoLaKoSz** [comment]
Should I make a PR?

**Comment by giovanni-orciuolo** [comment]
@PoLaKoSz yes!
